# https://taskfile.dev

version: '3'

vars:
  BASENAME: jg
  CONFIG: '{{.BASENAME}}-full.yaml'
  CONFIG_MIN: '{{.BASENAME}}-minimalist.yaml'
  CONFIG_CONTEXT: '{{.BASENAME}}-context.yaml'
  OMP_VERSION:
    sh: oh-my-posh --version
  SCHEMA_TAG: v{{.OMP_VERSION}}
  SCHEMA: schema-{{.SCHEMA_TAG}}.cue


tasks:
  default:
    cmds:
      - task: build
      - task: vet

  build:
    desc: Export CUE to config files.
    deps: [schema]
    sources:
      - "{{.BASENAME}}.cue"
      - "{{.SCHEMA}}"
    generates:
      - "{{.CONFIG}}"
      - "{{.CONFIG_MIN}}"
      - "{{.CONFIG_CONTEXT}}"
    cmds:
      - cue export --expression configs.full -o {{.CONFIG}}
      - cue export --expression configs.minimalist -o {{.CONFIG_MIN}}
      - cue export --expression configs.context -o {{.CONFIG_CONTEXT}}

  vet:
    desc: Validate that config files conform to the upstream oh-my-posh schema.
    deps: [schema]
    cmds:
      - cue vet {{.CONFIG}} {{.SCHEMA}}
      - cue vet {{.CONFIG_MIN}} {{.SCHEMA}}
      - cue vet {{.CONFIG_CONTEXT}} {{.SCHEMA}}

  schema:
    desc: Download oh-my-posh JSON schema and convert to CUE.
    status:
      - test -r {{.SCHEMA}}
      - test -s {{.SCHEMA}}
    cmds:
      - "curl -sL {{.SCHEMA_URL}} | cue import jsonschema: - --package {{.CUE_PKG}} -o {{.SCHEMA}}"
    vars:
      CUE_PKG: omp
      SCHEMA_URL: https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/{{.SCHEMA_TAG}}/themes/schema.json

  clean:
    desc: Remove generated files.
    cmds:
      - rm -f jg*.{yaml,toml} schema*
