alias ngdo="npm doc"
alias ngex="npm explore -g"
alias ngin="$sudocmd npm install -g"
alias ngll="npm ll -g 2>/dev/null"
alias ngls="npm ls -g --depth=0 2>/dev/null"
alias ngup="$sudocmd -E npm update -g"
alias ngrm="$sudocmd npm remove -g"
alias ngvi="npm view"
