# https://taskfile.dev

version: '3'

vars:
  OUT: mods.yml

tasks:
  default: [{task: export}]
  export: cue export --out yaml --outfile {{.OUT}} --force
  clean: rm -f {{.OUT}}
  test: mods 'what is this file?' < mods.cue
